library(shiny)
library(dplyr)
library(ggplot2)

shinyUI(fluidPage(
  
  # Application title
  titlePanel("Central Limit Theorem"),
  br(),
  p("The central limit theorem states that the distribution of averages of independent and identically
    distributed variables becomes that of a standard normal as the sample size increases."), 
  p("This application verifies the CLT by the simulation of large numbers of exponentials."), 
  
  p("First we need to define how many exponentials will be generated at each simulation."),
  p("Next we define how many simulations will be run, in this case, the more simulations the better
    the approximation will be."),
  p("Finally, exponentials are generated by the 'lambda' parameter which we define in the third input. "),
  p("With the 'Show normal distribution' checkbox we can choose to plot a standard normal distribution
    in the background to compare with the distribution of the simulated data."),
  br(),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(
        numericInput("exponentials",
                   "How many exponentials should be generated?",
                   min = 10, max = 100, value = 40, step = 1),
        numericInput("simulations",
                   "How many simulations should be executed?",
                   min = 50, max = 2000, value = 1000, step = 50),
        numericInput("lambda",
                   "What value of lambda should we use?",
                   min = 0.1, max = 1.0, value = 0.2, step = 0.1),
        checkboxInput("showNormal", "Show normal distribution?", value = TRUE)
    ),
    
    # Show a plot of the generated distribution
    mainPanel(
        h3("Distribution of averages of exponentials"),
        plotOutput("distPlot")
    )
  )
))
